In [2]:
%pip install pandas

Requirement already satisfied: pandas in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
%pip install yfinance

Collecting yfinance
  Downloading yfinance-1.7.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (4.15.0)
Collecting curl_cffi>=0.15 (from yfinance)
  Downloading curl_cffi-0.16.3-cp310-abi3-win_amd64.whl.metadata (17 kB)
Collecting lxml>=4.9.0 (from yfinance)
  Downloading lxml-6.1.3-cp314-cp314-win_amd64.whl.metadata (3.4 kB)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.13-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: numpy>=1.16.5 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (2.5.3)
Requirement already satisfied: pandas>=1.3.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (3.0.6)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-4.5.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: platformdirs>=2.0.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (4.11.11)
Collecting protobuf>=3.19.0 (from yfinance)
  Downloading protobuf-7.36.2-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting pytz>=2022.5 (from yfinance)
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: requests>=2.31 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (2.34.2)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-17.1-cp314-cp314-win_amd64.whl.metadata (6.5 kB)
Requirement already satisfied: soupsieve>=1.6.1 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Requirement already satisfied: cffi>=2.0.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2.1.1)
Requirement already satisfied: certifi>=2024.2.2 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.7.22)
Requirement already satisfied: pycparser in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=1.3.0->yfinance) (2026.4)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.31->yfinance) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.31->yfinance) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.31->yfinance) (2.8.0)
Downloading yfinance-1.7.0-py3-none-any.whl (149 kB)
Downloading curl_cffi-0.16.3-cp310-abi3-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 2.0/2.0 MB 27.3 MB/s  0:00:00
Downloading lxml-6.1.3-cp314-cp314-win_amd64.whl (4.1 MB)
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   ---------------------------------------- 4.1/4.1 MB 65.9 MB/s  0:00:00
Downloading multitasking-0.0.13-py3-none-any.whl (16 kB)
Downloading peewee-4.5.1-py3-none-any.whl (193 kB)
Downloading protobuf-7.36.2-cp310-abi3-win_amd64.whl (456 kB)
Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
Downloading websockets-17.1-cp314-cp314-win_amd64.whl (217 kB)
Installing collected packages: pytz, multitasking, websockets, protobuf, peewee, lxml, curl_cffi, yfinance

   ---------------------------------------- 0/8 [pytz]
   ---------- ----------------------------- 2/8 [websockets]
   ---------- ----------------------------- 2/8 [websockets]
   ---------- ----------------------------- 2/8 [websockets]
   --------------- ------------------------ 3/8 [protobuf]
   --------------- ------------------------ 3/8 [protobuf]
   --------------- ------------------------ 3/8 [protobuf]
   --------------- ------------------------ 3/8 [protobuf]
   -------------------- ------------------- 4/8 [peewee]
   -------------------- ------------------- 4/8 [peewee]
   ------------------------- -------------- 5/8 [lxml]
   ------------------------- -------------- 5/8 [lxml]
   ------------------------------ --------- 6/8 [curl_cffi]
   ------------------------------ --------- 6/8 [curl_cffi]
   ----------------------------------- ---- 7/8 [yfinance]
   ----------------------------------- ---- 7/8 [yfinance]
   ---------------------------------------- 8/8 [yfinance]

Successfully installed curl_cffi-0.16.3 lxml-6.1.3 multitasking-0.0.13 peewee-4.5.1 protobuf-7.36.2 pytz-2026.3.post1 websockets-17.1 yfinance-1.7.0
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script websockets.exe is installed in 'C:\Users\Joe\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts pwiz.exe and pwmigrate.exe are installed in 'C:\Users\Joe\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script curl-cffi.exe is installed in 'C:\Users\Joe\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [23]:
import pandas as pd
import numpy as np
import yfinance as yf
import time

# -----------------------------
# SCREENING PARAMETERS
# -----------------------------

# CAPM / WACC assumptions
RISK_FREE_RATE = 0.040
EQUITY_RISK_PREMIUM = 0.050
CORPORATE_TAX_RATE = 0.21

# Market capitalization screen
MIN_MARKET_CAP = 1.0e9
MAX_MARKET_CAP = 20.0e9

# Revenue growth requirement
MIN_REVENUE_CAGR = 0.10

# IMPORTANT:
# Yahoo Finance currently returns a maximum of
# 4 annual financial-statement observations.
# Therefore, use a true 3-year CAGR.
REVENUE_CAGR_YEARS = 3

# ROIC/WACC screen
MIN_ROIC_WACC >= 1.6

# Minimum invested capital
MIN_INVESTED_CAPITAL = 50e6

# Small pause between companies to reduce stress on Yahoo Finance
REQUEST_DELAY = 0.20

# Excluded sectors
EXCLUDED_SECTORS = {
    "Financial Services",
    "Financials",
    "Real Estate"
}

print("Imports and screening settings loaded.")

Imports and screening settings loaded.

In [24]:
SP400_URL = "https://en.wikipedia.org/wiki/List_of_S%26P_400_companies"


def get_sp400_tickers():
    """
    Downloads the current S&P MidCap 400 constituent list
    from Wikipedia.

    Uses browser-style headers to avoid HTTP 403 errors.
    """

    try:

        # Browser-style header
        headers = {
            "User-Agent": (
                "Mozilla/5.0 "
                "(Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 "
                "(KHTML, like Gecko) "
                "Chrome/120.0 Safari/537.36"
            )
        }

        # Read all tables from the page
        tables = pd.read_html(
            SP400_URL,
            storage_options=headers
        )

        constituent_table = None

        # Find the table containing the S&P 400 members
        for table in tables:

            # Clean column names
            table.columns = [
                str(col).strip()
                for col in table.columns
            ]

            # The constituent table should contain
            # a Symbol column and roughly 400 rows
            if (
                "Symbol" in table.columns
                and len(table) >= 350
            ):

                constituent_table = table.copy()
                break

        if constituent_table is None:

            raise ValueError(
                "Could not find the S&P 400 constituent table."
            )

        # Extract ticker symbols
        tickers = (
            constituent_table["Symbol"]
            .astype(str)
            .str.strip()

            # Yahoo Finance uses "-" rather than "."
            # for tickers such as BRK.B -> BRK-B
            .str.replace(
                ".",
                "-",
                regex=False
            )

            .drop_duplicates()
            .tolist()
        )

        print(
            f"Successfully loaded "
            f"{len(tickers)} S&P 400 tickers."
        )

        return tickers


    except Exception as e:

        print(
            "Error retrieving S&P 400 ticker list:"
        )

        print(e)

        return []


# -----------------------------------------
# CREATE WATCHLIST
# -----------------------------------------

WATCHLIST = get_sp400_tickers()


# -----------------------------------------
# CHECK RESULTS
# -----------------------------------------

print()
print(
    f"Number of stocks in WATCHLIST: "
    f"{len(WATCHLIST)}"
)

print()
print("First 20 tickers:")

print(
    WATCHLIST[:20]
)

Successfully loaded 400 S&P 400 tickers.

Number of stocks in WATCHLIST: 400

First 20 tickers:
['AA', 'AAL', 'AAON', 'ACI', 'ACM', 'ADC', 'AEIS', 'AFG', 'AGCO', 'AHR', 'AIT', 'ALGM', 'ALK', 'ALLY', 'ALSN', 'ALV', 'AM', 'AMG', 'AMH', 'AMKR']

In [25]:
def safe_number(value):
    """
    Converts a value to a finite float.
    Returns None if conversion is not possible.
    """

    try:
        value = float(value)

        if np.isfinite(value):
            return value

        return None

    except (TypeError, ValueError):
        return None


def latest_statement_value(statement, possible_names):
    """
    Finds the most recent available value for one of several
    possible financial statement line-item names.
    """

    if statement is None or statement.empty:
        return None

    for name in possible_names:

        if name in statement.index:

            row = statement.loc[name]

            # Handle duplicate rows if they occur
            if isinstance(row, pd.DataFrame):
                row = row.iloc[0]

            row = pd.to_numeric(
                row,
                errors="coerce"
            ).dropna()

            if row.empty:
                continue

            # Yahoo normally supplies dates as columns.
            try:
                row = row.sort_index(ascending=False)
            except Exception:
                pass

            value = safe_number(row.iloc[0])

            if value is not None:
                return value

    return None


def normalize_beta(raw_beta):
    """
    Shrinks observed beta toward 1.0.

    Adjusted Beta =
    67% observed beta + 33% market beta

    Beta is capped between 0.50 and 2.00.
    """

    beta = safe_number(raw_beta)

    if beta is None or beta <= 0:
        return 1.0

    adjusted_beta = (
        0.67 * beta
        + 0.33 * 1.0
    )

    return float(
        np.clip(
            adjusted_beta,
            0.50,
            2.00
        )
    )


def calculate_wacc(
    info,
    balance_sheet,
    income_statement,
    market_cap
):
    """
    Calculates Weighted Average Cost of Capital.
    """

    # -------------------------
    # Cost of equity
    # -------------------------

    beta = normalize_beta(
        info.get("beta")
    )

    cost_of_equity = (
        RISK_FREE_RATE
        + beta * EQUITY_RISK_PREMIUM
    )

    # -------------------------
    # Debt
    # -------------------------

    total_debt = safe_number(
        info.get("totalDebt")
    )

    if total_debt is None or total_debt <= 0:

        total_debt = latest_statement_value(
            balance_sheet,
            [
                "Total Debt",
                "Long Term Debt And Capital Lease Obligation",
                "Long Term Debt"
            ]
        )

    if total_debt is None:
        total_debt = 0.0

    # -------------------------
    # Interest expense
    # -------------------------

    interest_expense = latest_statement_value(
        income_statement,
        [
            "Interest Expense",
            "Interest Expense Non Operating"
        ]
    )

    if interest_expense is not None:
        interest_expense = abs(interest_expense)
    else:
        interest_expense = 0.0

    # -------------------------
    # Cost of debt
    # -------------------------

    if total_debt > 0 and interest_expense > 0:

        cost_of_debt = (
            interest_expense
            / total_debt
        )

        # Guard against unusual accounting values
        cost_of_debt = float(
            np.clip(
                cost_of_debt,
                RISK_FREE_RATE,
                0.12
            )
        )

    else:

        # Default assumed spread of 2%
        cost_of_debt = (
            RISK_FREE_RATE
            + 0.02
        )

    cost_of_debt_after_tax = (
        cost_of_debt
        * (1 - CORPORATE_TAX_RATE)
    )

    # -------------------------
    # Capital weights
    # -------------------------

    capital_base = (
        market_cap
        + total_debt
    )

    if capital_base <= 0:
        return None

    weight_equity = (
        market_cap
        / capital_base
    )

    weight_debt = (
        total_debt
        / capital_base
    )

    wacc = (
        weight_equity * cost_of_equity
        + weight_debt * cost_of_debt_after_tax
    )

    # Conservative minimum WACC
    return max(wacc, 0.055)


def calculate_roic(
    income_statement,
    balance_sheet
):
    """
    ROIC = NOPAT / Invested Capital

    NOPAT = EBIT × (1 - tax rate)

    Invested Capital =
    Total Assets
    - Current Liabilities
    - Cash
    """

    if (
        income_statement is None
        or balance_sheet is None
        or income_statement.empty
        or balance_sheet.empty
    ):
        return None

    # -------------------------
    # EBIT
    # -------------------------

    ebit = latest_statement_value(
        income_statement,
        [
            "Operating Income",
            "EBIT"
        ]
    )

    if ebit is None or ebit <= 0:
        return None

    nopat = (
        ebit
        * (1 - CORPORATE_TAX_RATE)
    )

    # -------------------------
    # Total assets
    # -------------------------

    total_assets = latest_statement_value(
        balance_sheet,
        [
            "Total Assets"
        ]
    )

    if total_assets is None:
        return None

    # -------------------------
    # Current liabilities
    # -------------------------

    current_liabilities = latest_statement_value(
        balance_sheet,
        [
            "Current Liabilities",
            "Total Current Liabilities"
        ]
    )

    if current_liabilities is None:
        current_liabilities = 0.0

    # -------------------------
    # Cash
    # -------------------------

    cash = latest_statement_value(
        balance_sheet,
        [
            "Cash And Cash Equivalents",
            "Cash Cash Equivalents And Short Term Investments",
            "Cash Financial"
        ]
    )

    if cash is None:
        cash = 0.0

    # -------------------------
    # Invested capital
    # -------------------------

    invested_capital = (
        total_assets
        - current_liabilities
        - cash
    )

    if invested_capital < MIN_INVESTED_CAPITAL:
        return None

    roic = (
        nopat
        / invested_capital
    )

    return roic


def check_revenue_cagr(
    income_statement,
    years=3
):
    """
    Calculates revenue CAGR.

    Pass requirement:
    CAGR > MIN_REVENUE_CAGR

    A company is not automatically rejected because
    one individual year had lower revenue.
    """

    if (
        income_statement is None
        or income_statement.empty
    ):
        return None, False, 0

    if "Total Revenue" not in income_statement.index:
        return None, False, 0

    revenue = income_statement.loc[
        "Total Revenue"
    ]

    if isinstance(revenue, pd.DataFrame):
        revenue = revenue.iloc[0]

    revenue = pd.to_numeric(
        revenue,
        errors="coerce"
    ).dropna()

    number_of_observations = len(revenue)

    observations_needed = years + 1

    if number_of_observations < observations_needed:

        return (
            None,
            False,
            number_of_observations
        )

    # Convert column dates
    revenue.index = pd.to_datetime(
        revenue.index
    )

    # Oldest to newest
    revenue = revenue.sort_index()

    # Use most recent 4 observations
    revenue = revenue.iloc[
        -observations_needed:
    ]

    beginning_revenue = float(
        revenue.iloc[0]
    )

    ending_revenue = float(
        revenue.iloc[-1]
    )

    if (
        beginning_revenue <= 0
        or ending_revenue <= 0
    ):

        return (
            None,
            False,
            number_of_observations
        )

    # CAGR
    cagr = (
        ending_revenue
        / beginning_revenue
    ) ** (1 / years) - 1

    # Main growth requirement
    growth_pass = (
        cagr > MIN_REVENUE_CAGR
    )

    return (
        cagr,
        growth_pass,
        number_of_observations
    )


print("Financial calculation functions loaded.")

Financial calculation functions loaded.

In [32]:
def run_screener(
    tickers,
    output_prefix="sp400"
):

    passed = []
    rejected = []

    total = len(tickers)

    for number, sym in enumerate(
        tickers,
        start=1
    ):

        print(
            f"[{number}/{total}] {sym}: ",
            end=""
        )

        company = sym
        sector = ""

        try:

            # -------------------------
            # Create Yahoo ticker
            # -------------------------

            ticker = yf.Ticker(sym)

            # -------------------------
            # Company information
            # -------------------------

            info = ticker.get_info()

            if not info:
                raise ValueError(
                    "Yahoo returned no company information."
                )

            company = info.get(
                "shortName",
                sym
            )

            sector = info.get(
                "sector",
                ""
            )

            country = info.get(
                "country",
                ""
            )

            # -------------------------
            # FILTER 1
            # Sector
            # -------------------------

            if sector in EXCLUDED_SECTORS:

                reason = (
                    f"Excluded sector: {sector}"
                )

                rejected.append({
                    "Ticker": sym,
                    "Company": company,
                    "Reason": reason
                })

                print(reason)

                continue

            # -------------------------
            # FILTER 2
            # Market capitalization
            # -------------------------

            market_cap = safe_number(
                info.get("marketCap")
            )

            if market_cap is None:

                reason = (
                    "Missing market capitalization"
                )

                rejected.append({
                    "Ticker": sym,
                    "Company": company,
                    "Reason": reason
                })

                print(reason)

                continue

            if not (
                MIN_MARKET_CAP
                <= market_cap
                <= MAX_MARKET_CAP
            ):

                reason = (
                    "Market cap outside "
                    "$1B-$20B range"
                )

                rejected.append({
                    "Ticker": sym,
                    "Company": company,
                    "Reason": reason
                })

                print(
                    f"{reason} "
                    f"(${market_cap / 1e9:.2f}B)"
                )

                continue

            # -------------------------
            # FILTER 3
            # United States
            # -------------------------

            if country != "United States":

                reason = (
                    f"Country = {country}"
                )

                rejected.append({
                    "Ticker": sym,
                    "Company": company,
                    "Reason": reason
                })

                print(reason)

                continue

            # -------------------------
            # Download financials
            # only after basic filters
            # -------------------------

            income_statement = (
                ticker.get_income_stmt(
                    freq="yearly",
                    pretty=True
                )
            )

            balance_sheet = (
                ticker.get_balance_sheet(
                    freq="yearly",
                    pretty=True
                )
            )

            if (
                income_statement.empty
                or balance_sheet.empty
            ):

                reason = (
                    "Financial statements unavailable"
                )

                rejected.append({
                    "Ticker": sym,
                    "Company": company,
                    "Reason": reason
                })

                print(reason)

                continue

            # -------------------------
            # FILTER 4
            # Revenue CAGR
            # -------------------------

            (
                revenue_cagr,
                growth_pass,
                revenue_observations
            ) = check_revenue_cagr(
                income_statement
            )

            if revenue_cagr is None:

                reason = (
                    f"Insufficient revenue history: "
                    f"{revenue_observations} annual "
                    f"observations; "
                    f"{REVENUE_CAGR_YEARS + 1} required"
                )

                rejected.append({
                    "Ticker": sym,
                    "Company": company,
                    "Reason": reason
                })

                print(reason)

                continue

            if not growth_pass:

                reason = (
                     f"Revenue CAGR below "
                     f"{MIN_REVENUE_CAGR * 100:.0f}%"
                )

                rejected.append({
                    "Ticker": sym,
                    "Company": company,
                    "Reason": reason
                })

                print(
                    f"{reason} "
                    f"(CAGR = "
                    f"{revenue_cagr * 100:.2f}%)"
                )

                continue

            # -------------------------
            # WACC
            # -------------------------

            wacc = calculate_wacc(
                info,
                balance_sheet,
                income_statement,
                market_cap
            )

            if wacc is None:

                reason = (
                    "Could not calculate WACC"
                )

                rejected.append({
                    "Ticker": sym,
                    "Company": company,
                    "Reason": reason
                })

                print(reason)

                continue

            # -------------------------
            # ROIC
            # -------------------------

            roic = calculate_roic(
                income_statement,
                balance_sheet
            )

            if roic is None:

                reason = (
                    "Could not calculate ROIC"
                )

                rejected.append({
                    "Ticker": sym,
                    "Company": company,
                    "Reason": reason
                })

                print(reason)

                continue

            # -------------------------
            # FILTER 5
            # ROIC / WACC
            # -------------------------

            economic_spread_ratio = (
                roic / wacc
            )

            if economic_spread_ratio < MIN_ROIC_WACC:

                reason = (
                    f"ROIC/WACC below "
                    f"{MIN_ROIC_WACC}"
                )

                rejected.append({
                    "Ticker": sym,
                    "Company": company,
                    "Reason": reason
                })

                print(
                    f"{reason} "
                    f"({economic_spread_ratio:.2f})"
                )

                continue

            # -------------------------
            # COMPANY PASSES
            # -------------------------

            passed.append({

                "Ticker":
                    sym,

                "Company":
                    company,

                "Sector":
                    sector,

                "Market Cap ($B)":
                    round(
                        market_cap / 1e9,
                        2
                    ),

                "Revenue CAGR Years":
                    REVENUE_CAGR_YEARS,

                "Revenue CAGR (%)":
                    round(
                        revenue_cagr * 100,
                        2
                    ),

                "ROIC (%)":
                    round(
                        roic * 100,
                        2
                    ),

                "Adjusted WACC (%)":
                    round(
                        wacc * 100,
                        2
                    ),

                "ROIC/WACC Ratio":
                    round(
                        economic_spread_ratio,
                        2
                    )
            })

            print(
                "PASS "
                f"| CAGR "
                f"{revenue_cagr * 100:.2f}% "
                f"| ROIC "
                f"{roic * 100:.2f}% "
                f"| WACC "
                f"{wacc * 100:.2f}% "
                f"| Ratio "
                f"{economic_spread_ratio:.2f}"
            )

        except Exception as e:

            reason = (
                f"Yahoo/data error: {e}"
            )

            rejected.append({
                "Ticker": sym,
                "Company": company,
                "Reason": reason
            })

            print(reason)

        finally:

            time.sleep(
                REQUEST_DELAY
            )

    # -----------------------------
    # Build final DataFrames
    # -----------------------------

    passed_columns = [
        "Ticker",
        "Company",
        "Sector",
        "Market Cap ($B)",
        "Revenue CAGR Years",
        "Revenue CAGR (%)",
        "ROIC (%)",
        "Adjusted WACC (%)",
        "ROIC/WACC Ratio"
    ]

    rejected_columns = [
        "Ticker",
        "Company",
        "Reason"
    ]

    passed_df = pd.DataFrame(
        passed,
        columns=passed_columns
    )

    rejected_df = pd.DataFrame(
        rejected,
        columns=rejected_columns
    )

    # Sort qualifying companies
    if not passed_df.empty:

        passed_df = (
            passed_df
            .sort_values(
                by="ROIC/WACC Ratio",
                ascending=False
            )
            .reset_index(drop=True)
        )

    # Sort rejected companies
    if not rejected_df.empty:

        rejected_df = (
            rejected_df
            .sort_values(
                by="Ticker"
            )
            .reset_index(drop=True)
        )

    # -----------------------------
    # Save CSV files
    # -----------------------------

    passed_df.to_csv(
        f"{output_prefix}_screen_passed.csv",
        index=False
    )

    rejected_df.to_csv(
        f"{output_prefix}_screen_rejected.csv",
        index=False
    )

    return passed_df, rejected_df


print("Screener function loaded.")

Screener function loaded.

In [33]:
results, rejected = run_screener(
    WATCHLIST,
    output_prefix="sp400"
)

print("\n-----------------------------")
print("SCREEN COMPLETE")
print("-----------------------------")

print(
    f"Stocks screened: {len(WATCHLIST)}"
)

print(
    f"Stocks passing: {len(results)}"
)

print(
    f"Stocks rejected: {len(rejected)}"
)

print("\nQUALIFYING STOCKS:")

display(results)

[1/400] AA: Revenue CAGR below 10% (CAGR = 1.01%)
[2/400] AAL: Revenue CAGR below 10% (CAGR = 3.71%)
[3/400] AAON: ROIC/WACC below 1.6 (0.90)
[4/400] ACI: Revenue CAGR below 10% (CAGR = 2.32%)
[5/400] ACM: Revenue CAGR below 10% (CAGR = 7.07%)
[6/400] ADC: Excluded sector: Real Estate
[7/400] AEIS: Revenue CAGR below 10% (CAGR = -0.85%)
[8/400] AFG: Excluded sector: Financial Services
[9/400] AGCO: Revenue CAGR below 10% (CAGR = -7.29%)
[10/400] AHR: Excluded sector: Real Estate
[11/400] AIT: Revenue CAGR below 10% (CAGR = 4.02%)
[12/400] ALGM: Revenue CAGR below 10% (CAGR = -2.95%)
[13/400] ALK: ROIC/WACC below 1.6 (0.58)
[14/400] ALLY: Excluded sector: Financial Services
[15/400] ALSN: Revenue CAGR below 10% (CAGR = 2.82%)
[16/400] ALV: Country = Sweden
[17/400] AM: Revenue CAGR below 10% (CAGR = 8.32%)
[18/400] AMG: Excluded sector: Financial Services
[19/400] AMH: Excluded sector: Real Estate
[20/400] AMKR: Revenue CAGR below 10% (CAGR = -1.84%)
[21/400] AN: Revenue CAGR below 10% (CAGR = 0.79%)
[22/400] ANF: PASS | CAGR 12.51% | ROIC 32.95% | WACC 7.85% | Ratio 4.20
[23/400] APG: Revenue CAGR below 10% (CAGR = 6.45%)
[24/400] APPF: PASS | CAGR 26.31% | ROIC 25.42% | WACC 8.47% | Ratio 3.00
[25/400] AR: Revenue CAGR below 10% (CAGR = -15.47%)
[26/400] ARMK: ROIC/WACC below 1.6 (0.85)
[27/400] ARW: Revenue CAGR below 10% (CAGR = -5.98%)
[28/400] ARWR: ROIC/WACC below 1.6 (0.75)
[29/400] ASB: Excluded sector: Financial Services
[30/400] ASH: Revenue CAGR below 10% (CAGR = -8.63%)
[31/400] ATI: Market cap outside $1B-$12B range ($25.49B)
[32/400] ATR: Revenue CAGR below 10% (CAGR = 4.37%)
[33/400] AVAV: Could not calculate ROIC
[34/400] AVNT: Revenue CAGR below 10% (CAGR = -1.36%)
[35/400] AVT: Revenue CAGR below 10% (CAGR = 1.36%)
[36/400] AVTR: Revenue CAGR below 10% (CAGR = -4.46%)
[37/400] AXTA: Revenue CAGR below 10% (CAGR = 1.57%)
[38/400] AYI: Revenue CAGR below 10% (CAGR = 2.75%)
[39/400] BAH: Revenue CAGR below 10% (CAGR = 6.60%)
[40/400] BBWI: Revenue CAGR below 10% (CAGR = -1.20%)
[41/400] BC: Revenue CAGR below 10% (CAGR = -7.66%)
[42/400] BCO: Revenue CAGR below 10% (CAGR = 5.07%)
[43/400] BDC: Revenue CAGR below 10% (CAGR = 1.37%)
[44/400] BHF: Excluded sector: Financial Services
[45/400] BILL: ROIC/WACC below 1.6 (0.04)
[46/400] BIO: Revenue CAGR below 10% (CAGR = -2.68%)
[47/400] BJ: Revenue CAGR below 10% (CAGR = 3.57%)
[48/400] BKH: Revenue CAGR below 10% (CAGR = -3.26%)
[49/400] BMRN: ROIC/WACC below 1.6 (1.04)
[50/400] BRKR: ROIC/WACC below 1.6 (0.46)
[51/400] BROS: ROIC/WACC below 1.6 (0.43)
[52/400] BRX: Excluded sector: Real Estate
[53/400] BSY: ROIC/WACC below 1.6 (1.40)
[54/400] BTSG: ROIC/WACC below 1.6 (0.49)
[55/400] BURL: Revenue CAGR below 10% (CAGR = 9.95%)
[56/400] BWA: Revenue CAGR below 10% (CAGR = 4.25%)
[57/400] BWXT: ROIC/WACC below 1.6 (1.11)
[58/400] BYD: Revenue CAGR below 10% (CAGR = 4.80%)
[59/400] CACI: ROIC/WACC below 1.6 (1.14)
[60/400] CAR: Revenue CAGR below 10% (CAGR = -4.28%)
[61/400] CART: PASS | CAGR 13.62% | ROIC 18.44% | WACC 8.31% | Ratio 2.22
[62/400] CAVA: ROIC/WACC below 1.6 (0.63)
[63/400] CBSH: Excluded sector: Financial Services
[64/400] CBT: Revenue CAGR below 10% (CAGR = -4.93%)
[65/400] CCK: Revenue CAGR below 10% (CAGR = -1.51%)
[66/400] CDE: Market cap outside $1B-$12B range ($20.66B)
[67/400] CDP: Excluded sector: Real Estate
[68/400] CELH: ROIC/WACC below 1.6 (1.20)
[69/400] CFR: Excluded sector: Financial Services
[70/400] CG: Excluded sector: Financial Services
[71/400] CGNX: Revenue CAGR below 10% (CAGR = -0.39%)
[72/400] CHDN: ROIC/WACC below 1.6 (1.37)
[73/400] CHE: Revenue CAGR below 10% (CAGR = 5.82%)
[74/400] CHH: Revenue CAGR below 10% (CAGR = 4.43%)
[75/400] CHRD: ROIC/WACC below 1.6 (0.20)
[76/400] CHWY: Revenue CAGR below 10% (CAGR = 7.59%)
[77/400] CLF: Revenue CAGR below 10% (CAGR = -6.80%)
[78/400] CLH: Revenue CAGR below 10% (CAGR = 5.29%)
[79/400] CMC: Missing market capitalization
[80/400] CNH: Market cap outside $1B-$12B range ($22.14B)
[81/400] CNM: Revenue CAGR below 10% (CAGR = 4.76%)
[82/400] CNO: Excluded sector: Financial Services
[83/400] CNX: Revenue CAGR below 10% (CAGR = -18.27%)
[84/400] COKE: Revenue CAGR below 10% (CAGR = 5.24%)
[85/400] COLB: Excluded sector: Financial Services
[86/400] COLM: Revenue CAGR below 10% (CAGR = -0.65%)
[87/400] CPRI: Country = United Kingdom
[88/400] CR: Revenue CAGR below 10% (CAGR = 9.07%)
[89/400] CRBG: Excluded sector: Financial Services
[90/400] CROX: Revenue CAGR below 10% (CAGR = 4.36%)
[91/400] CRS: Revenue CAGR below 10% (CAGR = 7.00%)
[92/400] CRUS: Revenue CAGR below 10% (CAGR = 1.72%)
[93/400] CSL: Revenue CAGR below 10% (CAGR = -2.70%)
[94/400] CTRE: Excluded sector: Real Estate
[95/400] CUBE: Excluded sector: Real Estate
[96/400] CUZ: Excluded sector: Real Estate
[97/400] CVLT: PASS | CAGR 14.69% | ROIC 25.42% | WACC 7.71% | Ratio 3.30
[98/400] CW: Market cap outside $1B-$12B range ($20.35B)
[99/400] CXT: Revenue CAGR below 10% (CAGR = 7.33%)
[100/400] CYTK: Revenue CAGR below 10% (CAGR = -2.36%)
[101/400] DAR: Revenue CAGR below 10% (CAGR = -2.06%)
[102/400] DBX: Revenue CAGR below 10% (CAGR = 2.74%)
[103/400] DCI: Missing market capitalization
[104/400] DINO: Revenue CAGR below 10% (CAGR = -11.07%)
[105/400] DKS: ROIC/WACC below 1.6 (1.30)
[106/400] DLB: Revenue CAGR below 10% (CAGR = 2.47%)
[107/400] DOCN: ROIC/WACC below 1.6 (1.27)
[108/400] DOCS: PASS | CAGR 15.45% | ROIC 22.65% | WACC 9.82% | Ratio 2.31
[109/400] DOCU: Revenue CAGR below 10% (CAGR = 8.57%)
[110/400] DT: ROIC/WACC below 1.6 (1.47)
[111/400] DTM: ROIC/WACC below 1.6 (0.70)
[112/400] DUOL: PASS | CAGR 41.08% | ROIC 26.47% | WACC 8.58% | Ratio 3.08
[113/400] DY: ROIC/WACC below 1.6 (0.91)
[114/400] EEFT: Revenue CAGR below 10% (CAGR = 8.11%)
[115/400] EGP: Excluded sector: Real Estate
[116/400] EHC: PASS | CAGR 10.92% | ROIC 13.46% | WACC 6.89% | Ratio 1.95
[117/400] ELAN: Revenue CAGR below 10% (CAGR = 2.25%)
[118/400] ELF: ROIC/WACC below 1.6 (0.59)
[119/400] ELS: Excluded sector: Real Estate
[120/400] ENS: Revenue CAGR below 10% (CAGR = 0.38%)
[121/400] ENSG: ROIC/WACC below 1.6 (1.17)
[122/400] ENTG: Market cap outside $1B-$12B range ($22.71B)
[123/400] EPR: Excluded sector: Real Estate
[124/400] EQH: Excluded sector: Financial Services
[125/400] ESAB: Revenue CAGR below 10% (CAGR = 3.10%)
[126/400] ESNT: Excluded sector: Financial Services
[127/400] EVR: Excluded sector: Financial Services
[128/400] EWBC: Excluded sector: Financial Services
[129/400] EXEL: PASS | CAGR 12.93% | ROIC 29.86% | WACC 7.04% | Ratio 4.24
[130/400] EXLS: PASS | CAGR 13.92% | ROIC 20.12% | WACC 7.93% | Ratio 2.54
[131/400] EXP: Revenue CAGR below 10% (CAGR = 2.43%)
[132/400] EXPO: Revenue CAGR below 10% (CAGR = 4.28%)
[133/400] FAF: Excluded sector: Financial Services
[134/400] FBIN: Revenue CAGR below 10% (CAGR = -1.87%)
[135/400] FCFS: Excluded sector: Financial Services
[136/400] FCN: Revenue CAGR below 10% (CAGR = 7.75%)
[137/400] FFIN: Excluded sector: Financial Services
[138/400] FHI: Excluded sector: Financial Services
[139/400] FHN: Excluded sector: Financial Services
[140/400] FIVE: ROIC/WACC below 1.6 (1.35)
[141/400] FLG: Excluded sector: Financial Services
[142/400] FLR: Revenue CAGR below 10% (CAGR = 4.10%)
[143/400] FLS: Revenue CAGR below 10% (CAGR = 9.37%)
[144/400] FN: Country = Cayman Islands
[145/400] FNB: Excluded sector: Financial Services
[146/400] FND: Revenue CAGR below 10% (CAGR = 3.18%)
[147/400] FNF: Excluded sector: Financial Services
[148/400] FOUR: ROIC/WACC below 1.6 (0.68)
[149/400] FR: Excluded sector: Real Estate
[150/400] FTI: Market cap outside $1B-$12B range ($28.01B)
[151/400] G: Country = Bermuda
[152/400] GAP: Revenue CAGR below 10% (CAGR = -0.54%)
[153/400] GATX: ROIC/WACC below 1.6 (0.46)
[154/400] GBCI: Excluded sector: Financial Services
[155/400] GEF: Revenue CAGR below 10% (CAGR = -7.80%)
[156/400] GGG: Revenue CAGR below 10% (CAGR = 1.43%)
[157/400] GHC: Revenue CAGR below 10% (CAGR = 7.77%)
[158/400] GLPI: Excluded sector: Real Estate
[159/400] GME: Revenue CAGR below 10% (CAGR = -15.08%)
[160/400] GMED: ROIC/WACC below 1.6 (1.13)
[161/400] GNTX: Revenue CAGR below 10% (CAGR = 9.71%)
[162/400] GPK: Revenue CAGR below 10% (CAGR = -2.99%)
[163/400] GWRE: ROIC/WACC below 1.6 (0.90)
[164/400] GXO: ROIC/WACC below 1.6 (0.67)
[165/400] H: Revenue CAGR below 10% (CAGR = 6.42%)
[166/400] HAE: Revenue CAGR below 10% (CAGR = 4.51%)
[167/400] HALO: PASS | CAGR 28.38% | ROIC 28.63% | WACC 7.82% | Ratio 3.66
[168/400] HGV: Revenue CAGR below 10% (CAGR = 9.59%)
[169/400] HIMS: ROIC/WACC below 1.6 (0.45)
[170/400] HL: ROIC/WACC below 1.6 (1.34)
[171/400] HLI: Excluded sector: Financial Services
[172/400] HLNE: Excluded sector: Financial Services
[173/400] HOG: Revenue CAGR below 10% (CAGR = -8.06%)
[174/400] HOMB: Excluded sector: Financial Services
[175/400] HQY: ROIC/WACC below 1.6 (1.42)
[176/400] HR: Excluded sector: Real Estate
[177/400] HRB: Revenue CAGR below 10% (CAGR = 4.35%)
[178/400] HWC: Excluded sector: Financial Services
[179/400] HXL: Revenue CAGR below 10% (CAGR = 6.28%)
[180/400] IBOC: Excluded sector: Financial Services
[181/400] IDA: Revenue CAGR below 10% (CAGR = 3.32%)
[182/400] IDCC: PASS | CAGR 22.13% | ROIC 63.56% | WACC 10.29% | Ratio 6.18
[183/400] IESC: PASS | CAGR 15.88% | ROIC 36.38% | WACC 11.56% | Ratio 3.15
[184/400] ILMN: Market cap outside $1B-$12B range ($37.18B)
[185/400] INGR: Revenue CAGR below 10% (CAGR = -3.15%)
[186/400] IPGP: Revenue CAGR below 10% (CAGR = -11.12%)
[187/400] IRT: Excluded sector: Real Estate
[188/400] ITT: Missing market capitalization
[189/400] JAZZ: Country = Ireland
[190/400] JEF: Excluded sector: Financial Services
[191/400] JLL: Excluded sector: Real Estate
[192/400] KBH: Revenue CAGR below 10% (CAGR = -3.33%)
[193/400] KBR: Revenue CAGR below 10% (CAGR = 5.86%)
[194/400] KD: Revenue CAGR below 10% (CAGR = -3.94%)
[195/400] KEX: Revenue CAGR below 10% (CAGR = 6.50%)
[196/400] KNF: Revenue CAGR below 10% (CAGR = 7.47%)
[197/400] KNSL: Excluded sector: Financial Services
[198/400] KNX: Revenue CAGR below 10% (CAGR = 0.18%)
[199/400] KRC: Excluded sector: Real Estate
[200/400] KRG: Excluded sector: Real Estate
[201/400] KRYS: Insufficient revenue history: 4 annual observations; 4 required
[202/400] KTOS: ROIC/WACC below 1.6 (0.15)
[203/400] LAD: ROIC/WACC below 1.6 (1.14)
[204/400] LAMR: Excluded sector: Real Estate
[205/400] LEA: Revenue CAGR below 10% (CAGR = 3.64%)
[206/400] LECO: Revenue CAGR below 10% (CAGR = 4.02%)
[207/400] LFUS: Revenue CAGR below 10% (CAGR = -1.72%)
[208/400] LIVN: Country = United Kingdom
[209/400] LNTH: PASS | CAGR 18.13% | ROIC 16.24% | WACC 8.49% | Ratio 1.91
[210/400] LOPE: Revenue CAGR below 10% (CAGR = 6.67%)
[211/400] LPX: Revenue CAGR below 10% (CAGR = -11.10%)
[212/400] LSCC: Revenue CAGR below 10% (CAGR = -7.46%)
[213/400] LSTR: Revenue CAGR below 10% (CAGR = -13.92%)
[214/400] M: Revenue CAGR below 10% (CAGR = -3.85%)
[215/400] MANH: PASS | CAGR 12.13% | ROIC 408.13% | WACC 8.80% | Ratio 46.36
[216/400] MAT: Revenue CAGR below 10% (CAGR = -0.54%)
[217/400] MEDP: PASS | CAGR 20.12% | ROIC 313.79% | WACC 9.46% | Ratio 33.17
[218/400] MIDD: Revenue CAGR below 10% (CAGR = -7.41%)
[219/400] MKSI: Revenue CAGR below 10% (CAGR = 3.49%)
[220/400] MLI: Revenue CAGR below 10% (CAGR = 1.62%)
[221/400] MMS: Revenue CAGR below 10% (CAGR = 5.46%)
[222/400] MOG-A: Revenue CAGR below 10% (CAGR = 8.34%)
[223/400] MOH: PASS | CAGR 12.42% | ROIC 15.64% | WACC 6.95% | Ratio 2.25
[224/400] MORN: Excluded sector: Financial Services
[225/400] MP: Revenue CAGR below 10% (CAGR = -24.79%)
[226/400] MSA: Revenue CAGR below 10% (CAGR = 7.06%)
[227/400] MSM: Missing market capitalization
[228/400] MTDR: Revenue CAGR below 10% (CAGR = 4.58%)
[229/400] MTG: Excluded sector: Financial Services
[230/400] MTN: Revenue CAGR below 10% (CAGR = 5.48%)
[231/400] MTSI: Market cap outside $1B-$12B range ($21.35B)
[232/400] MTZ: ROIC/WACC below 1.6 (0.78)
[233/400] MUR: Revenue CAGR below 10% (CAGR = -13.94%)
[234/400] MUSA: Revenue CAGR below 10% (CAGR = -6.14%)
[235/400] MZTI: Revenue CAGR below 10% (CAGR = 1.93%)
[236/400] NBIX: PASS | CAGR 24.32% | ROIC 15.84% | WACC 7.01% | Ratio 2.26
[237/400] NEU: Revenue CAGR below 10% (CAGR = -0.48%)
[238/400] NFG: Revenue CAGR below 10% (CAGR = 1.38%)
[239/400] NJR: Revenue CAGR below 10% (CAGR = -11.18%)
[240/400] NLY: Excluded sector: Real Estate
[241/400] NNN: Excluded sector: Real Estate
[242/400] NOV: Revenue CAGR below 10% (CAGR = 6.51%)
[243/400] NOVT: Revenue CAGR below 10% (CAGR = 4.43%)
[244/400] NTNX: ROIC/WACC below 1.6 (1.12)
[245/400] NVST: Revenue CAGR below 10% (CAGR = 1.91%)
[246/400] NVT: Market cap outside $1B-$12B range ($26.38B)
[247/400] NWE: Revenue CAGR below 10% (CAGR = 2.91%)
[248/400] NXST: Revenue CAGR below 10% (CAGR = -1.70%)
[249/400] NXT: PASS | CAGR 23.23% | ROIC 30.36% | WACC 12.07% | Ratio 2.51
[250/400] NYT: Revenue CAGR below 10% (CAGR = 6.96%)
[251/400] OC: Revenue CAGR below 10% (CAGR = 1.15%)
[252/400] OGE: Revenue CAGR below 10% (CAGR = -1.15%)
[253/400] OGS: Revenue CAGR below 10% (CAGR = -1.99%)
[254/400] OHI: Excluded sector: Real Estate
[255/400] OKTA: Market cap outside $1B-$12B range ($34.35B)
[256/400] OLED: Revenue CAGR below 10% (CAGR = 1.80%)
[257/400] OLLI: ROIC/WACC below 1.6 (1.59)
[258/400] OLN: Revenue CAGR below 10% (CAGR = -10.24%)
[259/400] ONB: Excluded sector: Financial Services
[260/400] ONTO: Revenue CAGR below 10% (CAGR = 0.00%)
[261/400] OPCH: PASS | CAGR 12.72% | ROIC 11.15% | WACC 6.58% | Ratio 1.70
[262/400] ORA: ROIC/WACC below 1.6 (0.40)
[263/400] ORI: Excluded sector: Financial Services
[264/400] OSK: Revenue CAGR below 10% (CAGR = 7.96%)
[265/400] OVV: Insufficient revenue history: 0 annual observations; 4 required
[266/400] OZK: Excluded sector: Financial Services
[267/400] P: Market cap outside $1B-$12B range ($36.19B)
[268/400] PAG: Revenue CAGR below 10% (CAGR = 4.57%)
[269/400] PATH: ROIC/WACC below 1.6 (0.35)
[270/400] PB: Excluded sector: Financial Services
[271/400] PBF: Revenue CAGR below 10% (CAGR = -14.44%)
[272/400] PCTY: PASS | CAGR 14.68% | ROIC 25.58% | WACC 7.13% | Ratio 3.59
[273/400] PEGA: Revenue CAGR below 10% (CAGR = 9.83%)
[274/400] PEN: ROIC/WACC below 1.6 (1.30)
[275/400] PFGC: Revenue CAGR below 10% (CAGR = 5.82%)
[276/400] PII: Revenue CAGR below 10% (CAGR = -5.92%)
[277/400] PINS: ROIC/WACC below 1.6 (0.77)
[278/400] PK: Excluded sector: Real Estate
[279/400] PLNT: PASS | CAGR 12.23% | ROIC 12.75% | WACC 6.19% | Ratio 2.06
[280/400] PNFP: Excluded sector: Financial Services
[281/400] POR: ROIC/WACC below 1.6 (0.66)
[282/400] POST: ROIC/WACC below 1.6 (0.98)
[283/400] PPC: Revenue CAGR below 10% (CAGR = 1.93%)
[284/400] PR: ROIC/WACC below 1.6 (1.27)
[285/400] PRI: Excluded sector: Financial Services
[286/400] PSN: ROIC/WACC below 1.6 (1.29)
[287/400] PVH: Revenue CAGR below 10% (CAGR = -0.27%)
[288/400] QLYS: PASS | CAGR 10.96% | ROIC 46.45% | WACC 7.69% | Ratio 6.04
[289/400] R: Revenue CAGR below 10% (CAGR = 0.60%)
[290/400] RBA: ROIC/WACC below 1.6 (0.91)
[291/400] RBC: Revenue CAGR below 10% (CAGR = 8.39%)
[292/400] REXR: Excluded sector: Real Estate
[293/400] RGA: Excluded sector: Financial Services
[294/400] RGEN: Revenue CAGR below 10% (CAGR = -2.70%)
[295/400] RGLD: Market cap outside $1B-$12B range ($21.61B)
[296/400] RH: Revenue CAGR below 10% (CAGR = -1.42%)
[297/400] RLI: Excluded sector: Financial Services
[298/400] RMBS: ROIC/WACC below 1.6 (1.41)
[299/400] RNR: Excluded sector: Financial Services
[300/400] ROIV: Market cap outside $1B-$12B range ($27.71B)
[301/400] ROKU: Market cap outside $1B-$12B range ($22.87B)
[302/400] RPM: Revenue CAGR below 10% (CAGR = 2.71%)
[303/400] RRC: Revenue CAGR below 10% (CAGR = -17.55%)
[304/400] RRX: Revenue CAGR below 10% (CAGR = 4.38%)
[305/400] RS: Revenue CAGR below 10% (CAGR = -5.66%)
[306/400] RYAN: Excluded sector: Financial Services
[307/400] RYN: Excluded sector: Real Estate
[308/400] SAIA: Revenue CAGR below 10% (CAGR = 5.02%)
[309/400] SAIC: Revenue CAGR below 10% (CAGR = -1.95%)
[310/400] SAM: Revenue CAGR below 10% (CAGR = -2.04%)
[311/400] SANM: Revenue CAGR below 10% (CAGR = 0.87%)
[312/400] SARO: ROIC/WACC below 1.6 (1.09)
[313/400] SBRA: Excluded sector: Real Estate
[314/400] SCI: Revenue CAGR below 10% (CAGR = 1.60%)
[315/400] SEIC: Excluded sector: Financial Services
[316/400] SF: Excluded sector: Financial Services
[317/400] SFM: PASS | CAGR 11.20% | ROIC 18.03% | WACC 6.72% | Ratio 2.68
[318/400] SGI: ROIC/WACC below 1.6 (0.79)
[319/400] SHC: Revenue CAGR below 10% (CAGR = 5.05%)
[320/400] SIGI: Excluded sector: Financial Services
[321/400] SIRI: Revenue CAGR below 10% (CAGR = -1.68%)
[322/400] SITM: Revenue CAGR below 10% (CAGR = 4.82%)
[323/400] SLAB: Revenue CAGR below 10% (CAGR = -8.49%)
[324/400] SLGN: Revenue CAGR below 10% (CAGR = 0.37%)
[325/400] SLM: Excluded sector: Financial Services
[326/400] SMG: Revenue CAGR below 10% (CAGR = -4.54%)
[327/400] SMTC: ROIC/WACC below 1.6 (0.79)
[328/400] SN: Market cap outside $1B-$12B range ($23.85B)
[329/400] SNX: Missing market capitalization
[330/400] SOLS: Revenue CAGR below 10% (CAGR = 2.70%)
[331/400] SON: Revenue CAGR below 10% (CAGR = 8.67%)
[332/400] SPXC: ROIC/WACC below 1.6 (1.04)
[333/400] SR: Revenue CAGR below 10% (CAGR = 4.05%)
[334/400] SSB: Excluded sector: Financial Services
[335/400] SSD: Revenue CAGR below 10% (CAGR = 3.30%)
[336/400] ST: Revenue CAGR below 10% (CAGR = -2.76%)
[337/400] STAG: Excluded sector: Real Estate
[338/400] STRL: PASS | CAGR 12.06% | ROIC 26.76% | WACC 11.69% | Ratio 2.29
[339/400] STWD: Excluded sector: Real Estate
[340/400] SUI: Excluded sector: Real Estate
[341/400] SWX: Revenue CAGR below 10% (CAGR = -26.86%)
[342/400] SYNA: Revenue CAGR below 10% (CAGR = -4.05%)
[343/400] TCBI: Excluded sector: Financial Services
[344/400] TEX: Revenue CAGR below 10% (CAGR = 7.06%)
[345/400] THC: Market cap outside $1B-$12B range ($21.25B)
[346/400] THG: Excluded sector: Financial Services
[347/400] THO: Revenue CAGR below 10% (CAGR = -16.26%)
[348/400] TKR: Revenue CAGR below 10% (CAGR = 0.63%)
[349/400] TLN: ROIC/WACC below 1.6 (0.02)
[350/400] TNL: Revenue CAGR below 10% (CAGR = 4.07%)
[351/400] TOL: Revenue CAGR below 10% (CAGR = 2.19%)
[352/400] TOST: PASS | CAGR 31.10% | ROIC 29.18% | WACC 11.44% | Ratio 2.55
[353/400] TREX: Revenue CAGR below 10% (CAGR = 2.02%)
[354/400] TRU: Excluded sector: Financial Services
[355/400] TTC: Revenue CAGR below 10% (CAGR = -0.03%)
[356/400] TTEK: PASS | CAGR 15.81% | ROIC 17.43% | WACC 8.10% | Ratio 2.15
[357/400] TTMI: Revenue CAGR below 10% (CAGR = 5.22%)
[358/400] TWLO: Market cap outside $1B-$12B range ($43.40B)
[359/400] TXNM: Revenue CAGR below 10% (CAGR = -1.26%)
[360/400] TXRH: PASS | CAGR 13.55% | ROIC 14.98% | WACC 7.82% | Ratio 1.91
[361/400] UBSI: Excluded sector: Financial Services
[362/400] UFPI: Revenue CAGR below 10% (CAGR = -13.09%)
[363/400] UGI: Revenue CAGR below 10% (CAGR = -10.33%)
[364/400] ULS: Revenue CAGR below 10% (CAGR = 6.60%)
[365/400] UMBF: Excluded sector: Financial Services
[366/400] UNM: Excluded sector: Financial Services
[367/400] USFD: Market cap outside $1B-$12B range ($20.48B)
[368/400] UTHR: Market cap outside $1B-$12B range ($21.23B)
[369/400] VAL: ROIC/WACC below 1.6 (1.16)
[370/400] VC: Revenue CAGR below 10% (CAGR = 0.11%)
[371/400] VFC: Revenue CAGR below 10% (CAGR = -4.68%)
[372/400] VIAV: ROIC/WACC below 1.6 (0.74)
[373/400] VICR: Revenue CAGR below 10% (CAGR = 4.29%)
[374/400] VLY: Excluded sector: Financial Services
[375/400] VMI: Revenue CAGR below 10% (CAGR = -1.89%)
[376/400] VNO: Excluded sector: Real Estate
[377/400] VNOM: ROIC/WACC below 1.6 (0.62)
[378/400] VNT: Revenue CAGR below 10% (CAGR = -1.15%)
[379/400] VOYA: Excluded sector: Financial Services
[380/400] VVV: PASS | CAGR 11.43% | ROIC 13.61% | WACC 6.90% | Ratio 1.97
[381/400] WAL: Excluded sector: Financial Services
[382/400] WCC: Revenue CAGR below 10% (CAGR = 3.15%)

,Ticker,Company,Sector,Market Cap ($B),Revenue CAGR Years,Revenue CAGR (%),ROIC (%),Adjusted WACC (%),ROIC/WACC Ratio
0,MANH,"Manhattan Associates, Inc.",Technology,12.00,3,12.13,408.13,8.80,46.36
1,MEDP,"Medpace Holdings, Inc.",Healthcare,17.58,3,20.12,313.79,9.46,33.17
2,IDCC,"InterDigital, Inc.",Technology,8.54,3,22.13,63.56,10.29,6.18
3,QLYS,"Qualys, Inc.",Technology,6.38,3,10.96,46.45,7.69,6.04
4,EXEL,"Exelixis, Inc.",Healthcare,14.45,3,12.93,29.86,7.04,4.24
5,ANF,Abercrombie & Fitch Company,Consumer Cyclical,5.81,3,12.51,32.95,7.85,4.20
6,WING,Wingstop Inc.,Consumer Cyclical,2.85,3,24.91,35.39,9.00,3.93
7,HALO,"Halozyme Therapeutics, Inc.",Healthcare,12.96,3,28.38,28.63,7.82,3.66
8,PCTY,Paylocity Holding Corporation,Technology,8.07,3,14.68,25.58,7.13,3.59
9,CVLT,"Commvault Systems, Inc.",Technology,6.01,3,14.69,25.42,7.71,3.30
10,IESC,"IES Holdings, Inc.",Industrials,12.72,3,15.88,36.38,11.56,3.15
11,DUOL,"Duolingo, Inc.",Technology,6.91,3,41.08,26.47,8.58,3.08
12,APPF,"AppFolio, Inc.",Technology,7.31,3,26.31,25.42,8.47,3.00
13,SFM,"Sprouts Farmers Market, Inc.",Consumer Defensive,6.44,3,11.20,18.03,6.72,2.68
14,TOST,"Toast, Inc.",Technology,17.29,3,31.10,29.18,11.44,2.55
15,EXLS,"ExlService Holdings, Inc.",Technology,5.34,3,13.92,20.12,7.93,2.54
16,NXT,Nextpower Inc.,Technology,12.71,3,23.23,30.36,12.07,2.51
17,DOCS,"Doximity, Inc.",Healthcare,4.76,3,15.45,22.65,9.82,2.31
18,STRL,"Sterling Infrastructure, Inc.",Industrials,15.83,3,12.06,26.76,11.69,2.29
19,NBIX,"Neurocrine Biosciences, Inc.",Healthcare,14.52,3,24.32,15.84,7.01,2.26
20,MOH,Molina Healthcare Inc,Healthcare,10.01,3,12.42,15.64,6.95,2.25
21,CART,Maplebear Inc.,Consumer Cyclical,10.28,3,13.62,18.44,8.31,2.22
22,TTEK,"Tetra Tech, Inc.",Industrials,9.09,3,15.81,17.43,8.10,2.15
23,PLNT,"Planet Fitness, Inc.",Consumer Cyclical,3.21,3,12.23,12.75,6.19,2.06
24,VVV,Valvoline Inc.,Consumer Cyclical,3.58,3,11.43,13.61,6.90,1.97
25,EHC,Encompass Health Corporation,Healthcare,12.30,3,10.92,13.46,6.89,1.95
26,LNTH,"Lantheus Holdings, Inc.",Healthcare,6.55,3,18.13,16.24,8.49,1.91
27,TXRH,"Texas Roadhouse, Inc.",Consumer Cyclical,10.98,3,13.55,14.98,7.82,1.91
28,OPCH,"Option Care Health, Inc.",Healthcare,3.64,3,12.72,11.15,6.58,1.70

In [34]:
rejection_summary = (
    rejected["Reason"]
    .value_counts()
    .reset_index()
)

rejection_summary.columns = [
    "Reason",
    "Number of Stocks"
]

display(rejection_summary)

                                               Reason  Number of Stocks
0                              Revenue CAGR below 10%               191
1                 Excluded sector: Financial Services                59
2                                 ROIC/WACC below 1.6                56
3                        Excluded sector: Real Estate                31
4                   Market cap outside $1B-$12B range                20
5                       Missing market capitalization                 5
6                            Country = United Kingdom                 2
7                                    Country = Sweden                 1
8                            Could not calculate ROIC                 1
9                            Country = Cayman Islands                 1
10                                  Country = Bermuda                 1
11                                  Country = Ireland                 1
12  Insufficient revenue history: 4 annual observa...                 1
13  Insufficient revenue history: 0 annual observa...                 1